### ISSUE TITLE
овово

### ISSUE THREAD

**Issue by Palash1308** [hikariatama/Hikka#101]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [ ] 🐳 Docker
- [ ] 🌺 Other platform

- Hikka version: 

**Additional context**

**Comment by penggrin12** [comment]
ебейший баг
