### ISSUE TITLE
Hikka bug report

### ISSUE THREAD

**Issue by vsecoder** [hikariatama/Hikka#107]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
Hikka not work in new account

**To Reproduce**
1. Clone repo
2. Start Hikka
3. In web set up Hikka
4. See error(Hikka not working, but installed)

**Expected behavior**
A working user bot, creating a bot in @BotFather, but instead only a hikka-assets chat was created

**Screenshots**
![изображение](https://github.com/hikariatama/Hikka/assets/60792943/41a69e84-7746-4d21-882b-974d128cfd7c)
![изображение](https://github.com/hikariatama/Hikka/assets/60792943/21119114-9885-45c8-8e9a-30c8d53915f4)
![изображение](https://github.com/hikariatama/Hikka/assets/60792943/3eef47c3-719e-4595-871a-eab9a0291468)
![изображение](https://github.com/hikariatama/Hikka/assets/60792943/95b43c6f-fe0a-4633-b9d0-ca1a1082dfe2)

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [x] 🐳 Docker
- [x] 🌺 Other platform

- Hikka version: last

**Additional context**
I tried it through Docker and just in the VDS console, possibly due to the launch on the Oracle server, but most likely due to the fact that there is no Hikka on the account and there was no Hikka

**Comment by hikariatama** [comment]
I don't see any errors

**Comment by vsecoder** [comment]
Give my twink account?

**Comment by hikariatama** [comment]
Reopen when you have sufficient amount of logs
