### ISSUE TITLE
Add an argument `form` to `utils.asset_channel`

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#114]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
We can create an asset_channel currently but we cannot automatically create it as a forum, so we need to change that later. I Would like to have an option to already make it an forum.

https://github.com/hikariatama/Hikka/blob/ce1f24f03313f8500de671815dde065fc8d86897/hikka/utils.py#L731

**Additional context**
Something like that:
```
async def asset_channel(
    client: CustomTelegramClient,
    title: str,
    description: str,
    *,
    channel: bool = False,
    silent: bool = False,
    archive: bool = False,
    invite_bot: bool = False,
    avatar: typing.Optional[str] = None,
    ttl: typing.Optional[int] = None,
    forum: bool = false,
    _folder: typing.Optional[str] = None,
) -> typing.Tuple[Channel, bool]:
```

**Comment by hikariatama** [comment]
Idk why would you need this, but whatever

**Comment by hikariatama** [comment]
Resolved in https://github.com/hikariatama/Hikka/commit/f23e09a594b186ac1bbc9dd8ea018702ef04d6e9
