### ISSUE TITLE
Logger stops working after getting error 400/500 from aiogram

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#115]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
I dont know at which point but at some point the inlinebot isn't sending messages into the log channel anymore. The errors are still shown in the `.log`
The inlinebot is still working, since my modules still running i just dont recieve any log message in the log channel till restart. Trying to send a `logging.error("asdf")` with python.py also doesnt work. One of the annoying errors since i dont know if something needs my attention.

**To Reproduce**
Sadly dont know.

**Expected behavior**
Logger shouldnt stop writing in the log channel

**Userbot installation info:**
 - Platform:
- [x] 🐳 Docker

- Hikka version: 
1.6.3

**Comment by hikariatama** [comment]
I faced this issue myself. It occurs when telegram bot api throws and error to aiogram.

**Comment by hikariatama** [comment]
TODO: Restart the logging worker if it is stopped

**Comment by hikariatama** [comment]
Resolved in https://github.com/hikariatama/Hikka/commit/f23e09a594b186ac1bbc9dd8ea018702ef04d6e9
