### ISSUE TITLE
inline menu in forums

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#117]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
Input in forums doesnt work.

**To Reproduce**
1. .config
2. choose any module with "input vaule"
3. click on input value
4. nothing happens

**Expected behavior**
normal input menu with the @<botname> <random things> <input>

**Userbot installation info:**
 - Platform:
- [x] 🐳 Docker

- Hikka version: 
1.6.3

**Comment by hikariatama** [comment]
This is a bug related to Telegram client itself, not Hikka.
