### ISSUE TITLE
UnitHeta does not open the inline form properly

### ISSUE THREAD

**Issue by logopek** [hikariatama/Hikka#119]
This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
UnitHeta crashes when special words in argument
**To Reproduce**
1. Type command "heta exit" or "heta block"

**Expected behavior**
UnitHeta find module with any mention of this word
**Logs**
```
  File "/home/y/Hikka/hikka/dispatcher.py", line 698, in future_dispatcher
    await func(message)
  File "<core hikka.modules.unit_heta>", line 187, in hetacmd
    message_id, peer, _, _ = resolve_inline_message_id(form.inline_message_id)
AttributeError: 'bool' object has no attribute 'inline_message_id'
```
**Userbot installation info:**
 - Platform:
- [ +] 🌺 Other platform (Ubuntu WSL2)

- Hikka version: 
1.6.3 #ce1f24f
Hikka-TL: 2.0.4 #158
Hikka-Pyro: 2.0.103 #158

**Comment by hikariatama** [comment]
UnitHeta will be completely reworked in the upcoming update

**Comment by hikariatama** [comment]
Resolved in https://github.com/hikariatama/Hikka/commit/f23e09a594b186ac1bbc9dd8ea018702ef04d6e9
