### ISSUE TITLE
Unable to delete the custom security group due to not found error

### ISSUE THREAD

**Issue by egorhik5** [hikariatama/Hikka#120]
When one attempts to delete the security group, the error "the group does not exist" is thrown.
Solution: Restrict the group name to lowercase english characters and throw error if any other characters are provided.
_--_
Edited by maintainer.

**Comment by egorhik5** [comment]
а как изменить имя уже существующей группы?

**Comment by hikariatama** [comment]
Please, keep the discussion in English.

**Comment by egorhik5** [comment]
and how to change the names of an existing group

**Comment by hikariatama** [comment]
There is no such function yet.

**Comment by egorhik5** [comment]
and what to do with existing groups

**Comment by hikariatama** [comment]
Ignore them.

**Comment by egorhik5** [comment]
ok then please add the function to change the name of the group

**Comment by hikariatama** [comment]
Resolved in https://github.com/hikariatama/Hikka/commit/f23e09a594b186ac1bbc9dd8ea018702ef04d6e9
