### ISSUE TITLE
при удалении пользовательской группы пишет ошибку <Не найдена>

### ISSUE THREAD

**Issue by egorhik5** [hikariatama/Hikka#121]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Userbot installation info:**
 - Platform:
- [ ] ✌️ lavHost
- Hikka version: 
1.6.3 #ce1f24f
**Additional context**
I created a security group with a name in English, and when deleted it still writes not found

**Comment by hikariatama** [comment]
Copy of https://github.com/hikariatama/Hikka/issues/120
