### ISSUE TITLE
Remove external_bl.

### ISSUE THREAD

**Issue by please-dont-ban-me** [hikariatama/Hikka#124]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
Remove `external_bl` (branch v1.6.4).

**Additional context**
This does not contradict human rights, but on the contrary should protect them. The use of userbots is not prohibited in the Telegram Terms of Service and the Telegram API Terms of Service, as long as the person does not use them for spam. You have added a feature that will completely disable Hikka in certain chats without the ability to disable this filter (this is possible by changing the code, but not everyone will be able to do this due to lack of knowledge). Also, bypassing this function will result in a person being banned at the next level of protection. This is also wrong, but more acceptable than the inner layer.

**Comment by hikariatama** [comment]
This feature is not yet completely released, but in the future the ability to restrict the userbot usage in certain chats will be the owner's right as it should be. Iff the chat rules contain such restriction and the chat is approved by me (e.g. I clearly see the reason for userbots being disabled there), the chat will be added to blacklist
