### ISSUE TITLE
obj:`PointerDict` does not support generic dictionary methods

### ISSUE THREAD

**Issue by MuRuLOSE** [hikariatama/Hikka#125]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**If you specify a dictionary in self.pointer, it gives this error AttributeError: 'PointerList' object has no attribute 'keys'**

**To Reproduce**
1. In self.pointer, specify a dictionary (e.g `something = self.pointer("dict",{})`)
2. Use pointer (try update or something)
3. See error

**Expected behavior**
I thought pointer would have methods for the dictionary, but it turns out there are none

**Screenshots**
![изображение](https://github.com/hikariatama/Hikka/assets/134152147/a3210513-1f5f-4481-a739-d0979d9f7de5)

**Userbot installation info:**
 - Platform:
 - [X] 🌺 Other platform

- Hikka version: 1.6.3

**Comment by hikariatama** [comment]
Judging by the error messages, you tried to invoke `.keys()` method on `PointerList`, which is kinda non-default behavior. You cannot change the type of pointer after it is created. Added additional check in 1.6.4 to avoid such bugs in the future.
