### ISSUE TITLE
Predispatcher

### ISSUE THREAD

**Issue by MuRuLOSE** [hikariatama/Hikka#129]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Pre-dispatcher**
Pre-dispatcher for modules, you can change request, check something, then run request, I really need a pre-dispatcher

**Additional context**
Example:
```python
Class SomethingPreHandler(loader.PreDispatcher):
    async def __call__(
        call,
        request,
        data,
        **kwargs
    ):
        if something:
             return call(requesrt, data)
        else:
            pass
```

**Comment by hikariatama** [comment]
Closed until the sufficient example of a usecase is provided
