### ISSUE TITLE
Docker and HikkaHost priority in info command

### ISSUE THREAD

**Issue by vsecoder** [hikariatama/Hikka#130]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
Using the env Dockerfile and HIKKAHOST and DOCKER will be in the info Docker. Although HIKKAHOST runs on Docker

**To Reproduce**
1. Go to '[HikkaHost Dockerfile](https://github.com/hikkahost/docker/blob/main/Dockerfile)'
2. Look on crutch
3. More on screenshots

**Expected behavior**
I was expecting to see HikkaHost in info

**Screenshots**
![изображение](https://github.com/hikariatama/Hikka/assets/60792943/0b7cdd1d-7cbb-4e83-9e16-0338e4b05139)

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [x] 🐳 Docker
- [x] 🌼 HikkaHostr
- [ ] 🌺 Other platform

- Hikka version: v1.6.4

**Comment by hikariatama** [comment]
Fixed in 1.6.4
