### ISSUE TITLE
Python 3.12 compability issues

### ISSUE THREAD

**Issue by marat2509** [hikariatama/Hikka#137]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**

**To Reproduce**
1. Install Python 3.12+
2. Clone and start hikka
4. See error in building wheels for aiohttp (aiohttp [has](https://github.com/aio-libs/aiohttp/issues/7639) 3.12 support)

**Expected behavior**
Alternatively, increase the version of aiohttp in requirements.txt

**Userbot installation info:**
 - Platform:
- [x] 🕶️ Termux
- [ ] ✌️ lavHost
- [x] ☁️ Okteto
- [x] 🐳 Docker

 - [x] 🌺 Other platform
 
- Hikka version: 1.63

**Additional context**
Nothing

**Comment by hikariatama** [comment]
It's the issue with aiohttp C extensions. Set the env variable to disable their build and then install requirements.
