### ISSUE TITLE
Inline spotify dont open. 

### ISSUE THREAD

**Issue by pussyklller** [hikariatama/Hikka#18]
## Before continuing, check the mark below
- [*] This bug is related to **module from official [repository](https://mods.hikariatama.ru)**.
---
**Module, related to problem** [E.g. HikariChat]:
inline player ex DLC for Spotify Now
**Short description of the bug**: 
dont load inline player
**Steps to reproduce**: 
.splayer - > press open (dont react to pressing) 
**Any additional information**:
Spotify Now installerd, all req too, but inline addon dont work.

**Comment by hikariatama** [comment]
Fixed in 2.0.0
