### ISSUE TITLE
Del Phone Number on WebUI

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#24]
## Before continuing, check the mark below
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
Since the WebUI can add phones, it would be nice if it also could remove phones on the fly, without deleting files from the system (what is not always possible)

**Comment by hikariatama** [comment]
Implemented, will be added as `.uninstall_hikka` call to 1.0.23
