### ISSUE TITLE
No Button Hikka Info

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#25]
## Before continuing, check the mark below
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**

**To Reproduce**
1. Go to '.config'
2. Click on 'HikkaInfo'
3. Click on 'custom_button'
4. Click on 'enter value'
5. press inline message (so actually nothing as button)
6. it will create an error on .info

**Expected behavior**
Send .info just without a button

**Log**
  File "/hikka/dispatcher.py", line 448, in future_dispatcher
    await func(message)
  File "", line 137, in infocmd
IndexError: list index out of range

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [x] Docker

- Hikka version: 
Version: 1.1.22
Build: 3ed19805

**Additional context**

**Comment by hikariatama** [comment]
Will be fixed with next push
