### ISSUE TITLE
TCP Connection for Multiaccount in one Instance

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#27]
## Before continuing, check the mark below
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
I don't know how it is currently handled, but when I currently produce an error, the bot apparently tries to establish a TCP connection with all logged-in bots. On the one hand, this produces spam in the log and apparently the target also has some kind of DDoS protection, since not all of my accounts can connect and produce a timeout.

If the connection is tried even with a "no error", this is of course even more unnecessary traffic.

Only the necessary/triggered bots should try to establish a connection.

**Comment by hikariatama** [comment]
Should be fixed now

**Comment by anon97945** [comment]
I'll let you know if it persists.
