### ISSUE TITLE
silent_tags suggestions

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#31]
## Before continuing, check the mark below
- [x] **My suggestion is not about illegal stuff, doesn't violate Telegram EULA and human rights.**
---

**Short description of idea**:
In silent_tags.py there will be a message in the silent-tags group. Since i can't unread send my own messages I don't see when someone tagged me and I do need to check that group manually.

my idea is that the bot sends it instead of the user and so you can see an unread notification. So you can see directly and at a glance that you have been tagged. Since the group is muted anyway, you won't get a notification.

**If you have an existing implementation of this idea, e.g. in a another userbot, attach it here**:

**Any additional information**:
Reference: https://mods.hikariatama.ru/view/silent_tags.py

**Comment by hikariatama** [comment]
iirc you want to read the tag but keep it, correct? If you read the mention, messages will be read too, so there is no way to implement this, except of "Unread" mark on chat

**Comment by hikariatama** [comment]
fixed + added new features in 2.0.0

**Comment by anon97945** [comment]
Mark messages from blocked users in the silent-tags group read via config with `true/false`

**Comment by hikariatama** [comment]
[ ] Add option to silently ignore tags without logging

You can't mark a chosen messages as read, bc all messages below will be marked as well

**Comment by anon97945** [comment]
[ ] Add option to exclude groups by id from logging.

Stop logging the silent-group with spamgroups.

1234, 5678, 8901

**Comment by hikariatama** [comment]
`Ignore blocked users` can't be implemented bc telegram is shit and in order to get the user status (blocked or not) you need to make a very expensive request (getFullUser)

**Comment by hikariatama** [comment]
Added `ignore_bots`, `ignore_blocked`, `ignore_ids` to 2.0.2 (will be available when Hikka 1.1.23 is released)

**Comment by hikariatama** [comment]
Added `ignore_bots`, `ignore_blocked`, `ignore_users`, `ignore_chats`, `silent_bots`, `silent_blocked`, `silent_users`, `silent_chats` to 2.0.3. For futhermore suggestions reopen the issue

**Comment by anon97945** [comment]
![IMG_20220519_234013_279](https://user-images.githubusercontent.com/54719502/169409777-15cf1b1d-e77e-4bbc-b4f2-d674e318efb4.jpg)

Error in debug log.

**Comment by hikariatama** [comment]
fixed
