### ISSUE TITLE
Config Command Suggestion

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#36]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
.config can apply settings, which is awesome, but it should have some kind of `true`/`false` recognition or true/false. Right now i could use `tru` or `on` and will catch an error than. (example silent_tags.py). It could be checked when the .config says `Default: False`.

**Additional context**
Maybe something like this (or a better one)
```

> 
> def to_bool(value):
>     if str(value).lower() in ("true"):
>         return True
>     if str(value).lower() in ("false"):
>         return False


> if not isinstance(to_bool(args[1]), bool):
> 	return await utils.answer(message, self.strings("error", message))

**Comment by hikariatama** [comment]
Ig it would be better to add some kind of validator to `loader.ConfigValue`. E.g. `validator=loader.Boolean`

**Comment by anon97945** [comment]
If this would do the same, sure. I think you got my point. 👍🏻 
the problem is that you need to check whether the module use yes/no, true/flase, int or whatever. Thatswhy check if default: is an boolean and then apply that validator.

Or make modules able to help your loader by something like `possible arguements`

**Comment by hikariatama** [comment]
[ ] Add validators to `loader.ConfigValue`, inc. native ones aka loader.validators.Int, .Boolean etc and custom ones via lambda expressions

**Comment by hikariatama** [comment]
Added to local branch, will be added in 1.0.23
`loader.validators.Boolean`, `loader.validators.Integer`, `loader.validators.Choice`
