### ISSUE TITLE
 Hikka Suggestions

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#37]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
Change the restart message when the bot has fully loaded.

**Comment by hikariatama** [comment]
- [ ] Commit flag for silent pushes
- [ ] Rework .blacklist
- [ ] Whitelist for commands
- [ ] Targeted security (certain user, certain chat)
- [ ] .stopauth .startauth for web auth button
- [ ] client isolation (get rid of self.allclients somehow)
- [ ] Flag in settings to remove acc from sync (isolate it)
- [ ] Global configuration aka .dlmod --all

**Comment by anon97945** [comment]
* [ ]  Full uninstall of Hikka from an account. (Delete all Hikka related things. Bots, Chats etc.)

**Comment by anon97945** [comment]
* [ ] Ability to install system requirements via module

**Comment by hikariatama** [comment]
> * [ ]  Ability to install system requirements via module

.terminal pip3 install -y <req>

**Comment by anon97945** [comment]
* [ ] remove or replace with random phone and other private things from eval output. Like .e reply.sender (phone number)

**Comment by anon97945** [comment]
* [ ] Change the `🔄 Transferring value to userbot...` message on remote control.

**Comment by anon97945** [comment]
* [ ] show ID of the userbot which raise the error.
* [ ] Configurable per account (to not show every id of every account in the log due to privacy)

**Comment by hikariatama** [comment]
> * .ch_hikka_bot | should also have some "default" option, to random botname again.

I can't see any usecase of this feature

**Comment by hikariatama** [comment]
> * do not remove modules from loader db if they can't be loaded. An broken update removed all of my modules after restart. Annoying for multiple accounts to reload them

This is not possible, bc modules in db are updates with ones from `self.allmodules.modules`, where there are no "not-loaded" modules

**Comment by hikariatama** [comment]
> * Add lang validator

Lang formats are different. Use `loader.validators.String` or `loader.validators.RegExp` for more complex langs

**Comment by anon97945** [comment]
* [ ] Add permissions cache: perms = await self._client.get_permissions(chat, user) and the ability to force (recache) get the perms with (chat, user, force)

**Comment by anon97945** [comment]
* [ ] add cache for `await message.client(GetFullChannelRequest(channel=<id>))`
* [ ] add cache for `await message.client.get_permissions(chat, user)`

**Comment by anon97945** [comment]
* [ ] Show Version of the module in `.help <module>`

**Comment by anon97945** [comment]
* [ ] `await utils.asset_channel(client, "Title", "Description", channel=<group/channel/megagroup>)` Let us choose the type of chat to create and search for.

**Comment by hikariatama** [comment]
* [ ] Force bound method `_mod_get` and `_mod_set` to use module classname instead of strings'es `name` + Legacy migration

**Comment by hikariatama** [comment]
> * [x]  `await utils.asset_channel(client, "Title", "Description", channel=<group/channel/megagroup>)` Let us choose the type of chat to create and search for.

Apparently, this function is for creation of `asset-channels`, which are commonly used only to _store assets_, not to create group chats.

**Comment by hikariatama** [comment]
> * [ ]  add cache for `await message.client(GetFullChannelRequest(channel=<id>))`

I don't wanna make cacher for raw api methods, bc sometimes you need to forcefully get a non-cached (actual) result, which with cached raw methods will be impossible.
But

* [ ] Add cache for `client.get_permissions` sounds good

**Comment by anon97945** [comment]
* [ ] utils.answer | utils.answer native string support of `<br>` (replace it with `\n`) right in utils.answer or so.
* [ ] `.langforce <langcode> <id>` | Add support for forced languages of modules in given chats. Example: German communitys and English communitys. Let Hikka load all strings of the module on start and then check if the chatid, which triggers an command, has a forced language. If yes, use it, else use default userbot lanaguage. Same goes for if string isn't found in that language. Idea behind: not all of my german community is speaking english, nor is the english community speaking german. So i need to host 2 Userbots with the same module just for translation......

**Comment by hikariatama** [comment]
> * `.langforce <langcode> <id>` | Add support for forced languages of modules in given chats. Example: German communitys and English communitys. Let Hikka load all strings of the module on start and then check if the chatid, which triggers an command, has a forced language. If yes, use it, else use default userbot lanaguage. Same goes for if string isn't found in that language. Idea behind: not all of my german community is speaking english, nor is the english community speaking german. So i need to host 2 Userbots with the same module just for translation......

There will be a multiple languages with priority soon, so it's not neccessary to create .langforce

**Comment by hikariatama** [comment]
> * utils.answer | utils.answer native string support of `<br>` (replace it with `\n`) right in utils.answer or so.

Why would anyone need it? =/

**Comment by anon97945** [comment]
> 

add multiple strings via config -> series(strings) and put them together as one big. since inline doesnt support unlimited message length.

**Comment by anon97945** [comment]
* [ ] asset_channel: on creation optional self-destructive setting by default (telegram native version)
