### ISSUE TITLE
Hikka Bugs

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#38]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**

* [X] alias still won't survive a reboot. (Fixed in 1.1.27)

🔮 Version: 1.1.24 #3453fb98

**Comment by anon97945** [comment]
* [ ] config bool of `share_link` in `loader` doesn't work.

**Comment by anon97945** [comment]
* [ ] `Loading inline form...` wont remove on anonymous user
* [ ] Config page won't update after putting value on anonymous user

**Comment by anon97945** [comment]
Maybe utils.answer bug.

`🚫 [ERROR] root: Error running watcher
Traceback (most recent call last):
  File "/hikka/dispatcher.py", line 455, in future_dispatcher
    await func(message)
  File "https://mods.hikariatama.ru/silent_tags.py", line 287, in watcher
    and message.sender.bot
AttributeError: 'Channel' object has no attribute 'bot'🚫 [ERROR] root: Error running watcher
Traceback (most recent call last):
  File "/hikka/dispatcher.py", line 455, in future_dispatcher
    await func(message)
  File "https://mods.hikariatama.ru/silent_tags.py", line 287, in watcher
    and message.sender.bot
AttributeError: 'Channel' object has no attribute 'bot'```

**Comment by hikariatama** [comment]
>  Config page won't update after putting value on anonymous user

Can't be fixed. Message has an attribute `out`, which determines if Anonymous message was sent by owner, but chosen inline query does not. Ergo you can't determine, whether this result was sent by owner

**Comment by anon97945** [comment]
* [ ] `db.set` creates `database` under `"name"` while `config` is saved under `<classname>` change to use only classnames instead having 2 database entries for one module. Also names change, classnames won't.

**Comment by sernot** [comment]
Help string for "fconfig" contains a typo "propery_name", which should probably be "property_name". 
Causing line: [link](https://github.com/hikariatama/Hikka/blob/12ae1ec44de07002938d882813581111aee75c14/hikka/modules/hikka_config.py#L749)
Found in 1.2.7 (at #12ae1ec4)

**Comment by anon97945** [comment]
* [ ] validator.py | Hidden Validator doesn't have remove/add buttons. Let them add after pressing `Show value` button. Also if its `validators.Hidden(validator=loader.validators.Series(validator=loader.validators.X))` it should be "Show value`s`"
* [ ] validator.py | `validators.Series(validator=loader.validators.String())` does save `\n` as `\\n` in the database. It is not shown in `.config` only in `.e db`. Problem is when you want to break the line...
* [ ] When aiogram `reset peer/timeout` etc, the inlinebot is still working but it will not send `error/info/etc` logs into the log channel till restart.

**Comment by anon97945** [comment]
* [ ] Library's default config after updating them via module load

**Comment by anon97945** [comment]
🎬 Code:
msg = await self.inline.bot.send_message(
    f"-100{message.chat.id}",
    "blabla",
    parse_mode="HTML",
)
await msg.delete()

🚫 Error:

🪐 Full stack:

👉 <core python>:59 in ecmd
👉 __init__.py:86 in meval
    r = await locs["tmp"](**kwargs)
👉 <string>:6 in tmp
👉 message.py:2986 in delete
    return await self.bot.delete_message(self.chat.id, self.message_id)
👉 base.py:161 in bot
    raise RuntimeError("Can't get bot instance from context. "

😵 RuntimeError: Can't get bot instance from context. You can fix it with setting current instance: 'Bot.set_current(bot_instance)'

**Comment by anon97945** [comment]
* [ ] `. ping` does not work on my multi user instance
