### ISSUE TITLE
Hikka Modules Suggestions

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#39]
- [x] **My suggestion is not about illegal stuff, doesn't violate Telegram EULA and human rights.**
---

silent_tags.py:
* [x] Add a global white/blacklist switch for id related configs.

**Comment by anon97945** [comment]
* [ ] limit backups via config to X backups and delete older

**Comment by anon97945** [comment]
* [ ] dnd_statuses.py | config to response in pm only.

**Comment by hikariatama** [comment]
> * [ ]  limit backups via config to X backups and delete older

The easiest way to achieve this behavior is to use internal Telegram feature "Auto-delete messages"
If you try to implement it via userbot, it will cause a lot of unnecessary API requests and ergo floodwaits and other bad stuff

**Comment by anon97945** [comment]
* [ ] add cache for `await message.client(GetFullChannelRequest(channel=<id>))`
* [ ] add cache for `await message.client.get_permissions(chat, user)`
