### ISSUE TITLE
123

### ISSUE THREAD

**Issue by etochesnok** [hikariatama/Hikka#40]
Йе, уроки закончились, значит сегодня суббота
Я захожу на Twitch и пишу кому-то в чат: «Поплачь, блядота»
Чтобы не плакала девочка надо написать пару пиздатых паст
Мне похуй на это, я очень классный пац, йе
Я захожу на Twitch и пишу всем оскорбления
Заниматься вот этой хуйнёй вообще-то мне честно не лень, бля
Я очень классный, я обожаю смотреть Братишкина и Мазеллова
Я ещё спорю чей чат намного пиздат чё, ну я считаю что у Мазеллова, реально
У Мазеллова самые охуенные треки, «Маз Корж» — изобретение века, ну что ж
Охуенно, спасибо, зачитал как бог, йе
Боже, как же он читает, как же он фристайлит, как мы его все понимаем, йе
— О, Жожо в чате, ты чё про Гаечку пиздел?
— Да я просто сидел и читал рэпак и сидел без дела, она зашла мне в чат, выписала какую-то хуйню в субботу, ну я ей просто сказал: «А ну-ка, ну-ка, поплачь, блядота», йе

[Припев]
Поплачь, блядота
Поплачь, блядота, у-у
Поплачь, блядота
Поплачь, сегодня суббота, йе
Поплачь, блядота
Поплачь, блядота, у-у
Поплачь блядота
Поплачь, ведь сегодня суббота, йе

[Куплет 2]
Очень классный пац
Сидим в TikTok'е, залипаем классно
Охуенные классные TikTok'и с Иваном Золо, во, мне не пофиг
Так нравятся TikTok'и Эвелона, он охуенно снимает и клёво
С кем-то там, с Некоглаем, ну, честно это хуйня нереальная, у-у

[Припев]
Поплачь блядота, кхм
Поплачь блядота
Поплачь блядота
Ведь сегодня суббота, о-о-о
Поплачь блядота
Поплачь блядота
Поплачь блядота
Хорошо, что сегодня суббота

[Куплет 3]
Я захожу на Twitch, посмотреть кто стримит
Я сижу один и дрочу за компом в своей квартире
Мне если честно вообще никто не нравится из стримеров в принципе
Но я считаю что лучше всех — это Дмитрий Ликс
Потому что он старый и классный
Старый и пиздатый
Старый и крутой
Старый и клёвый
Я мечтаю чтобы он был учителем в моей школе
Он очень классный чел, мне он очень нравится
Хочу чтоб Дмитрий Ликс меня прям выебал в задницу, йе

[Припев]
Поплачь блядота, у-у
Поплачь блядота
Поплачь блядота
Знаю что сегодня суббота, йе, йе
Поплачь блядота
Поплачь блядота
Поплачь блядота
Ведь сегодня суббота, хули

**Comment by 5050prop** [comment]
Гений

**Comment by plasticsummer** [comment]
шок, вонка признается в любви с твинка

**Comment by etochesnok** [comment]
уроки закончились значит сегодня суббота

**Comment by hikariatama** [comment]
Spam. Closed
