### ISSUE TITLE
Hikka 1.6.x wont run in a docker container

### ISSUE THREAD

**Issue by penggrin12** [hikariatama/Hikka#87]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
Nothing happens (no output) on starting hikka in a docker container on oracle

**To Reproduce**
1. Build a docker image from [this](https://nekobin.com/meminuxilo) Dockerfile
2. Run: `docker start (image id)`
3. After some time run: `docker logs (container id)` (or/and `docker ps` to see if that container is actually running or not)

**Expected behavior**
Expected to see a "Please visit x.x.x.x:8080" text

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [x] 🐳 Docker
- [ ] 🌺 Other platform

- Hikka version: latest master from [here](https://github.com/hikariatama/Hikka/)

**Comment by hikariatama** [comment]
Fixed in 1.6.1. Closed.
