### ISSUE TITLE
Add a header to mark whether the module will loaded by Hikka or not

### ISSUE THREAD

**Issue by iamnalinor** [hikariatama/Hikka#96]
- [x] My suggestion **is related to Hikka userbot itself**. It's not about illegal stuff, doesn't violate Telegram EULA and human rights and **is not related to modules**.
---
**Describe the suggestion**
Add `X-Hikka-Loader` header (or something else) when loader is downloading source code of module to load. This can be used to allow modules' authors to give Hikka users one version of module (e.g. with Hikka-only features usage) and another one to FTG/GeekTG users. It is going to be just adding one new line [here](https://github.com/hikariatama/Hikka/blob/7008b54869ad16f04f2a573d7c93379ceef82db5/hikka/_local_storage.py#L149).

**Additional context**
Also you may add a setting with which user can control whether do they really want to get another version of modules or not.

**Comment by hikariatama** [comment]
Serving different versions of code based on custom header makes code review impossible. If you want to provide Hikka-only functionality, use `hasattr(self, "hikka")` expression to check, whether the module is being loaded by Hikka or anything else
